const products = [

  // ─── G.I. Joe ─────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Duke Action Figure (Hasbro, 1984)",
    category: "G.I. Joe",
    categorySlug: "gi-joe",
    price: 32.00,
    condition: "Excellent",
    image: "images/products/product-1.jpg",
    bg: "linear-gradient(135deg, #1a2e1a 0%, #3b6b3b 100%)",
    emoji: "🪖",
    badge: null,
    inStock: true,
    featured: true,
    description: "Original Hasbro G.I. Joe Duke figure from the legendary 3¾\" line — all original accessories intact, tight joints, vibrant paint. The All-American hero of any vintage Joe collection, and he's reporting for duty."
  },
  {
    id: 2,
    name: "Snake Eyes Silent Missions Figure (1982)",
    category: "G.I. Joe",
    categorySlug: "gi-joe",
    price: 48.00,
    condition: "Mint",
    image: "images/products/product-2.jpg",
    bg: "linear-gradient(135deg, #111 0%, #333 100%)",
    emoji: "🥷",
    badge: null,
    inStock: true,
    featured: false,
    description: "The iconic all-black silent commando in remarkable shape — tight o-ring, no yellowing, original wolf not included but figure is flawless. Snake Eyes fans know this one doesn't come around clean very often."
  },
  {
    id: 3,
    name: "Cobra H.I.S.S. Tank Vehicle",
    category: "G.I. Joe",
    categorySlug: "gi-joe",
    price: 58.00,
    condition: "Good",
    image: "images/products/product-3.jpg",
    bg: "linear-gradient(135deg, #1a1a2e 0%, #333366 100%)",
    emoji: "🚗",
    badge: null,
    inStock: true,
    featured: false,
    description: "Cobra's signature H.I.S.S. tank in solid display shape — turret rotates, driver seat intact. Some play wear on the treads but looks menacing on any shelf. Destro would approve."
  },
  {
    id: 4,
    name: "Cobra Commander (Hood Version, 1982)",
    category: "G.I. Joe",
    categorySlug: "gi-joe",
    price: 22.00,
    condition: "Fair",
    image: "images/products/product-4.jpg",
    bg: "linear-gradient(135deg, #0a0a30 0%, #1a1a6e 100%)",
    emoji: "🦹",
    badge: null,
    inStock: true,
    featured: false,
    description: "The original hooded Cobra Commander — straight arms, the first version produced. Shows honest play wear which only proves this guy has been plotting world domination since the Reagan era. Cobra-la-la-la-la-la!"
  },

  // ─── Pokémon ───────────────────────────────────────────────────────────────
  {
    id: 5,
    name: "Charizard Base Set Holo #4/102",
    category: "Pokemon",
    categorySlug: "pokemon",
    price: 85.00,
    condition: "Excellent",
    image: "images/products/product-5.jpg",
    bg: "linear-gradient(135deg, #f6a135 0%, #e84d0e 100%)",
    emoji: "🔥",
    badge: "RARE",
    inStock: true,
    featured: true,
    description: "The card. The legend. Original Wizards of the Coast Charizard holo from the 1999 Base Set — light play wear with strong holo pattern and excellent centering. Every collection has a holy grail, and this is it."
  },
  {
    id: 6,
    name: "Pikachu Jungle Set 1st Edition Holo",
    category: "Pokemon",
    categorySlug: "pokemon",
    price: 45.00,
    condition: "Mint",
    image: "images/products/product-6.jpg",
    bg: "linear-gradient(135deg, #f6d365 0%, #f9a825 100%)",
    emoji: "⚡",
    badge: null,
    inStock: true,
    featured: false,
    description: "First Edition Pikachu holo from the Jungle set — crisp edges, no whitening, the 1st Edition stamp front and center. This little guy has been stored properly and it shows. Gotta catch 'em all, and this one's worth catching."
  },
  {
    id: 7,
    name: "Mewtwo Legendary Collection Reverse Holo",
    category: "Pokemon",
    categorySlug: "pokemon",
    price: 35.00,
    condition: "Good",
    image: "images/products/product-7.jpg",
    bg: "linear-gradient(135deg, #6a0dad 0%, #9b59b6 100%)",
    emoji: "✨",
    badge: null,
    inStock: true,
    featured: false,
    description: "Mewtwo Legendary Collection reverse holo — one of the most visually striking cards Wizards ever printed. Light surface scratches under direct light but the reverse holo treatment is absolutely beautiful. Psychic power at a fair price."
  },
  {
    id: 8,
    name: "1999 Hasbro Pikachu Plush (Original)",
    category: "Pokemon",
    categorySlug: "pokemon",
    price: 38.00,
    condition: "Excellent",
    image: "images/products/product-8.jpg",
    bg: "linear-gradient(135deg, #ffe066 0%, #ffb300 100%)",
    emoji: "🧸",
    badge: null,
    inStock: true,
    featured: false,
    description: "Original 1999 Hasbro Pikachu plush — the squatty, chunky boy from the first wave of Pokémon merchandise. Tags intact, no staining, still holds his shape. This is the Pikachu that started it all for a whole generation."
  },

  // ─── TMNT ──────────────────────────────────────────────────────────────────
  {
    id: 9,
    name: "Leonardo Original Playmates Figure (1988)",
    category: "TMNT",
    categorySlug: "tmnt",
    price: 18.00,
    condition: "Excellent",
    image: "images/products/product-9.jpg",
    bg: "linear-gradient(135deg, #003d1f 0%, #1a7a40 100%)",
    emoji: "🐢",
    badge: null,
    inStock: true,
    featured: true,
    description: "Original 1988 Playmates Leonardo with his signature blue mask and katana swords — tight waist swivel, clean paint on the shell. The leader of the group in solid shape. Cowabunga, dude."
  },
  {
    id: 10,
    name: "Shredder Action Figure (1988 Playmates)",
    category: "TMNT",
    categorySlug: "tmnt",
    price: 24.00,
    condition: "Good",
    image: "images/products/product-10.jpg",
    bg: "linear-gradient(135deg, #2c2c54 0%, #6c3483 100%)",
    emoji: "⚔️",
    badge: null,
    inStock: true,
    featured: false,
    description: "The Shredder from the original 1988 Playmates run — cape present, blades intact, some light scuffing on the chrome shoulder armor from a lifetime of villainy. Every turtle collection needs its nemesis."
  },
  {
    id: 11,
    name: "Bebop Action Figure (1988 Playmates)",
    category: "TMNT",
    categorySlug: "tmnt",
    price: 28.00,
    condition: "Fair",
    image: "images/products/product-11.jpg",
    bg: "linear-gradient(135deg, #4a3728 0%, #9e6b4a 100%)",
    emoji: "🐗",
    badge: null,
    inStock: true,
    featured: false,
    description: "Bebop the mutant warthog henchman from the original 1988 line — mohawk intact, showing honest play wear across the armor. Loose joints give him that relaxed, punky vibe he was always known for. Radical!"
  },
  {
    id: 12,
    name: "Turtle Party Wagon Vehicle (Playmates)",
    category: "TMNT",
    categorySlug: "tmnt",
    price: 68.00,
    condition: "Good",
    image: "images/products/product-12.jpg",
    bg: "linear-gradient(135deg, #1a472a 0%, #40916c 100%)",
    emoji: "🚐",
    badge: null,
    inStock: true,
    featured: false,
    description: "The iconic TMNT Party Wagon — both launchers functional, side panels fold out correctly, some scuffs on the body but she still rolls and she still parties. The turtles' getaway vehicle, ready to roll with a new crew."
  },

  // ─── Thundercats ───────────────────────────────────────────────────────────
  {
    id: 13,
    name: "Lion-O with Sword of Omens (LJN, 1985)",
    category: "Thundercats",
    categorySlug: "thundercats",
    price: 58.00,
    condition: "Excellent",
    image: "images/products/product-13.jpg",
    bg: "linear-gradient(135deg, #7f1d1d 0%, #ea580c 100%)",
    emoji: "🦁",
    badge: null,
    inStock: true,
    featured: true,
    description: "LJN's Lion-O with his extending Sword of Omens still functioning — the claw shield is present and the extend mechanism clicks properly. Strong, vivid paint and tight joints. Thunder, Thunder, Thundercats — hooooo!"
  },
  {
    id: 14,
    name: "Mumm-Ra the Ever-Living Figure (LJN, 1985)",
    category: "Thundercats",
    categorySlug: "thundercats",
    price: 48.00,
    condition: "Good",
    image: "images/products/product-14.jpg",
    bg: "linear-gradient(135deg, #1a0a2e 0%, #4a1a6e 100%)",
    emoji: "💀",
    badge: null,
    inStock: true,
    featured: false,
    description: "The Ancient Spirits of Evil's champion — Mumm-Ra the Ever-Living in the classic LJN sculpt with his bandaged mummy appearance. Some light play wear but the evil still radiates off this thing. A centerpiece for any vintage 80s shelf."
  },
  {
    id: 15,
    name: "Panthro Action Figure (LJN, 1985)",
    category: "Thundercats",
    categorySlug: "thundercats",
    price: 42.00,
    condition: "Good",
    image: "images/products/product-15.jpg",
    bg: "linear-gradient(135deg, #1a2a3a 0%, #2d6a8a 100%)",
    emoji: "🐾",
    badge: null,
    inStock: true,
    featured: false,
    description: "Panthro, the tough Thundercat mechanic, in the original LJN release — nunchucks present, paint holding strong, joints still serviceable. The strong silent type of the Thundercats roster, and harder to find than you'd think."
  },

  // ─── Video Games ───────────────────────────────────────────────────────────
  {
    id: 16,
    name: "Super Mario Bros. 3",
    category: "Video Games",
    categorySlug: "video-games",
    console: "NES",
    price: 35.00,
    condition: "Excellent",
    image: "images/products/product-16.jpg",
    bg: "linear-gradient(135deg, #c0392b 0%, #e74c3c 100%)",
    emoji: "🍄",
    badge: null,
    inStock: true,
    featured: true,
    description: "The pinnacle of NES platforming — Super Mario Bros. 3 cartridge cleaned, tested, and saving properly. Label is crisp with no writing or major damage. Possibly the greatest video game ever made, and this copy is ready to prove it."
  },
  {
    id: 17,
    name: "The Legend of Zelda: A Link to the Past",
    category: "Video Games",
    categorySlug: "video-games",
    console: "SNES",
    price: 48.00,
    condition: "Good",
    image: "images/products/product-17.jpg",
    bg: "linear-gradient(135deg, #1a5276 0%, #2e86c1 100%)",
    emoji: "🗡️",
    badge: null,
    inStock: true,
    featured: false,
    description: "Link to the Past on SNES — save battery is fresh, all three save files work, label shows light shelf wear. The Dark World awaits. A cornerstone of any serious retro collection and still one of the best games ever made."
  },
  {
    id: 18,
    name: "Sonic the Hedgehog 2",
    category: "Video Games",
    categorySlug: "video-games",
    console: "Genesis",
    price: 18.00,
    condition: "Excellent",
    image: "images/products/product-18.jpg",
    bg: "linear-gradient(135deg, #0d47a1 0%, #1976d2 100%)",
    emoji: "💨",
    badge: null,
    inStock: true,
    featured: false,
    description: "Sonic 2 on the Sega Genesis — the game that introduced Tails and multiplayer mode to the Blue Blur's saga. Cartridge pins clean, plays perfectly, label in great shape. Gotta go fast."
  },
  {
    id: 19,
    name: "GoldenEye 007",
    category: "Video Games",
    categorySlug: "video-games",
    console: "N64",
    price: 30.00,
    condition: "Good",
    image: "images/products/product-19.jpg",
    bg: "linear-gradient(135deg, #1a1a1a 0%, #4a4a2a 100%)",
    emoji: "🔫",
    badge: null,
    inStock: true,
    featured: false,
    description: "GoldenEye 007 for N64 — the FPS that defined a generation of couch multiplayer. Cartridge clean and tested, label shows typical N64-era shelf wear. Four controllers and a friend group not included, but the memories will come rushing back."
  },
  {
    id: 20,
    name: "Metal Gear Solid (Complete in Case)",
    category: "Video Games",
    categorySlug: "video-games",
    console: "PS1",
    price: 65.00,
    condition: "Excellent",
    image: "images/products/product-20.jpg",
    bg: "linear-gradient(135deg, #0a0a0a 0%, #2c3e50 100%)",
    emoji: "📟",
    badge: null,
    inStock: true,
    featured: false,
    description: "Metal Gear Solid on PS1, complete — both discs, manual, the fold-out Codec frequency card. All present. This is the game that proved video games could be cinema, and this copy is in the kind of shape Solid Snake would demand."
  },
  {
    id: 21,
    name: "Tetris",
    category: "Video Games",
    categorySlug: "video-games",
    console: "Game Boy",
    price: 22.00,
    condition: "Mint",
    image: "images/products/product-21.jpg",
    bg: "linear-gradient(135deg, #1a6b1a 0%, #2ecc71 100%)",
    emoji: "🟦",
    badge: null,
    inStock: true,
    featured: false,
    description: "Tetris for the original Game Boy — the pack-in classic that sold the system to millions. This copy is in remarkable shape, label nearly perfect, pins gleaming. Still the most addictive game ever made. Don't start unless you have time."
  },
  {
    id: 22,
    name: "Pitfall!",
    category: "Video Games",
    categorySlug: "video-games",
    console: "Atari 2600",
    price: 12.00,
    condition: "Fair",
    image: "images/products/product-22.jpg",
    bg: "linear-gradient(135deg, #5d4037 0%, #8b6914 100%)",
    emoji: "🌿",
    badge: null,
    inStock: true,
    featured: false,
    description: "Pitfall! on the Atari 2600 — one of the greatest games of the golden age of home gaming. Cartridge works perfectly, label has seen better days but the gameplay is timeless. Harry's been swinging on vines since 1982, and he's not stopping now."
  },

  // ─── Collectables ──────────────────────────────────────────────────────────
  {
    id: 23,
    name: "He-Man Masters of the Universe Figure (Mattel, 1981)",
    category: "Collectables",
    categorySlug: "collectables",
    price: 30.00,
    condition: "Good",
    image: "images/products/product-23.jpg",
    bg: "linear-gradient(135deg, #4a0e8f 0%, #c77dff 100%)",
    emoji: "⚔️",
    badge: null,
    inStock: true,
    featured: true,
    description: "Original Mattel He-Man figure from the Masters of the Universe line — sword included, rubbery limbs still pliable, paint holding strong. By the power of Grayskull, this one's been taken care of. A must for any 80s collector."
  },
  {
    id: 24,
    name: "Ghostbusters Slimer Figure (Kenner, 1986)",
    category: "Collectables",
    categorySlug: "collectables",
    price: 36.00,
    condition: "Excellent",
    image: "images/products/product-24.jpg",
    bg: "linear-gradient(135deg, #1a4a1a 0%, #39ff14 50%, #1a4a1a 100%)",
    emoji: "👻",
    badge: null,
    inStock: true,
    featured: false,
    description: "He slimed me — and now he can slime your shelf. Original Kenner Real Ghostbusters Slimer figure in excellent condition, bright green, no missing slime. The most lovable ghost in pop culture history, ready for a new home."
  },
  {
    id: 25,
    name: "Star Wars: Return of the Jedi Lunchbox (1983)",
    category: "Collectables",
    categorySlug: "collectables",
    price: 48.00,
    condition: "Fair",
    image: "images/products/product-13.jpg",
    bg: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    emoji: "🚀",
    badge: null,
    inStock: true,
    featured: false,
    description: "King-Seeley Thermos Return of the Jedi metal lunchbox from 1983 — Battle of Endor artwork on the front, thermos not included. Some light surface rust at the edges which is expected for a 40-year-old lunchbox. A genuine piece of Star Wars history."
  }

];
